environments:
  dev:
    project: bq-dataworkeragent-test
    region: us-central1
    variables:
      project: bq-dataworkeragent-test
      region: us-central1
    secrets:
      SALESFORCE_CLIENT_ID: "projects/{{ project }}/secrets/SALESFORCE_CLIENT_ID/versions/latest"
      SALESFORCE_CLIENT_SECRET: "projects/{{ project }}/secrets/SALESFORCE_CLIENT_SECRET/versions/latest"
      SALESFORCE_MY_DOMAIN: "projects/{{ project }}/secrets/SALESFORCE_MY_DOMAIN/versions/latest"
    resources:
      - type: bigquerydatatransfer.transferConfig
        name: salesforce_contract_ingest
        definition:
          displayName: "Salesforce Contract Ingestion"
          dataSourceId: salesforce
          schedule: "every 24 hours"
          destinationDatasetId: salesforce_ingest
          params:
            connector.authentication.oauth.clientId: "{{ SALESFORCE_CLIENT_ID }}"
            connector.authentication.oauth.clientSecret: "{{ SALESFORCE_CLIENT_SECRET }}"
            connector.authentication.oauth.myDomain: "{{ SALESFORCE_MY_DOMAIN }}"
            assets: ["Contract"]

      - type: dataform.repository.workflowConfig
        name: salesforce_workflow_config
        parent: salesforce_dbt_repo
        definition:
          releaseConfig: "projects/{{ project }}/locations/{{ region }}/repositories/salesforce_dbt_repo/releaseConfigs/salesforce_release"
          cronSchedule: "0 6 * * *"
          timeZone: "America/Los_Angeles"
