vini_dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: bq-dataworkeragent-test
      dataset: salesforce_cleansed
      threads: 4
      timeout_seconds: 300
      location: us-central1
