version: 2

sources:
  - name: salesforce_raw
    database: bq-dataworkeragent-test
    schema: salesforce_raw
    tables:
      - name: Contract
        description: "Raw Salesforce Contract data"

  - name: billing_5g
    database: bq-dataworkeragent-test
    schema: 5g_billing_dataset
    tables:
      - name: dim_network_serviceability
        description: "5G Coverage mapping by Zip Code"
      - name: fct_monthly_billing
        description: "Monthly Billing Data"
